### ISSUE TITLE
libcrypto-1_1-x64.dll and libssl-1_1-x64.dll are missing

### ISSUE THREAD

**Issue by bastien-martin** [nextcloud-releases/desktop#1]
Hello,

Updating NextCloud client for Windows 10 (64-bit) from 3.9.0 to 3.9.1 breaks NextCloud Client because of 2 missing files:

- libcrypto-1_1-x64.dll
- libssl-1_1-x64.dll

I've manually put these two files, from OpenSSL 1.1.1.4, on the root NextCloud client directory (C:\Program Files\Nextcloud) and it's working. With OpenSSL 1.1.1.7, it's not working.

Please fix this regression ASAP.

Thank you.

**Comment by bastien-martin** [comment]
Typo in version, it's 3.9.0 to 3.9.1 and not 1.9.0 to 1.9.1

**Comment by mgallien** [comment]
this has already been fixed and updated packages pushed
sorry for the trouble
please do not report issue on this repo as it was already reported some time ago in the real repository
