### ISSUE TITLE
Appimage - Client closes instantly after opening

### ISSUE THREAD

**Issue by MargauxM123** [nextcloud-releases/desktop#19]
Hello
I've downloaded the Appimage but it closes almost instantly after opening, like 5 seconds. It just has time to indicate how many files are waiting for synchronization, and then it closes.
I'm on Ubuntu 22.04.4 LTS
I'm not used to contribute on git, I hope I did everything well...

**Comment by tigernero79** [comment]
I think you may have the same unsolved problem as us. application closes if the destination of the files to be synchronized irsdsidete on external microsd see surface or external usb hd

https://github.com/nextcloud-releases/desktop/issues/13

**Comment by joshtrichards** [comment]
Hi @MargauxM123 - This repository is only used for release management. It's not used for development or bug reporting in the app itself. Please report your issues at the appropriate repository - https://github.com/nextcloud/desktop

Thanks!

@mgallien Can you (or someone with more appropriate permissions than me) turn off the *Issues* tab in this repository to prevent people from continuing to inadvertently open issues here? It's already toggled off for many of the others `nextcloud-releases` repos already.

**Comment by MargauxM123** [comment]
So sorry, thanks for the info !
