### ISSUE TITLE
v3.10.1 is automatically pushed to MacOS 10.14, even though it is incompatible

### ISSUE THREAD

**Issue by Golffies** [nextcloud-releases/desktop#3]
![Capture d’écran 2023-11-02 à 15 57 07](https://github.com/nextcloud-releases/desktop/assets/5718159/d13cb3ab-93cf-4a10-a18f-b1583a6e8ff7)
The problem is related but nevertheless differs from the one mentioned in #2.

- Observed malfunction

On MacOS 10.14, the automatic update tool replaces the existing version of the Nextcloud desktop client with version 3.10.1, even though this version is incompatible with this operating system.

As a result, after the update, the desktop client no longer works in the MacOS 10.14 environment, and the synchronisation service is interrupted without the user being notified.

- Expected behaviour

The automatic update tool should check the MacOS version before installing a new version of the desktop client. If the MacOS version does not meet the prerequisites, the update software should keep the existing version of Nextcloud Desktop in place and warn the user that the new version is incompatible with his operating system.

**Comment by arennertz** [comment]
This issue really crashed my day. Would love to see this fixed too!

**Comment by mgallien** [comment]
we are in the progress of having the client compatible again with older macOS releases
please keep in mind that using an OS version not supported by its vendor is usually not a so great idea
see https://github.com/nextcloud/desktop/pull/6207
there might other PR related to this

**Comment by mgallien** [comment]
closing it now as we would want to keep issues in the https://github.com/nextcloud/desktop/issues repository
