### ISSUE TITLE
Update to v.3.12.1 fails and virus detected

### ISSUE THREAD

**Issue by MiMoHo** [nextcloud-releases/desktop#4]
v3.12.1 can't be automatically updated, nor installed via pkg when the app is already installed.
When removing the app and running the installer, Avira detects a virus for v3.12.1 after installation completion:
![Avira Security blocked a threat](https://github.com/nextcloud-releases/desktop/assets/37556964/988264c8-e7a0-48e3-be16-20678e3fdf7b)

**Comment by expiredemulsion** [comment]
It appears to be a signing error.

Code signature scan of all bundles in the folder /Users/user/Desktop/test:

/Users/user/Desktop/test/Nextcloud.app error -67054 a sealed resource is missing or invalid
/Users/user/Desktop/test/Nextcloud.app isn't signed or recognised.
/Users/user/Desktop/test/Nextcloud.app/Contents/Frameworks/Sparkle.framework/Versions/A/Resources/Autoupdate.app is Notarized.

Found 1 bundle signing errors out of 55 scanned in /Users/user/Desktop/test
Checked at Friday, 8 March 2024 at 07:32:07 Central European Standard Time


Quarantine flag found: 0182
This is an app.
✅ No 32-bit only components were found.

App signature check:
⛔️ spctl error 3
/Users/user/Desktop/test/Nextcloud.app: rejected (invalid destination for symbolic link in bundle)
origin=Developer ID Application: Nextcloud GmbH (NKUJUXUJ3B)


codesign check:
Executable=/Users/user/Desktop/test/Nextcloud.app/Contents/MacOS/Nextcloud
Identifier=com.nextcloud.desktopclient
Format=app bundle with Mach-O universal (x86_64 arm64)
CodeDirectory v=20500 size=64743 flags=0x10000(runtime) hashes=2016+3 location=embedded
Hash type=sha256 size=32
CandidateCDHash sha256=8c195d739d507aa5a25dbd670c483ab7d6d1c190
CandidateCDHashFull sha256=8c195d739d507aa5a25dbd670c483ab7d6d1c1905b762369a3cda45453f4b247
Hash choices=sha256
CMSDigest=8c195d739d507aa5a25dbd670c483ab7d6d1c1905b762369a3cda45453f4b247
CMSDigestType=2
CDHash=8c195d739d507aa5a25dbd670c483ab7d6d1c190
Signature size=8978
Authority=Developer ID Application: Nextcloud GmbH (NKUJUXUJ3B)
Authority=Developer ID Certification Authority
Authority=Apple Root CA
Timestamp=6 Mar 2024 at 12:47:28
Info.plist entries=22
TeamIdentifier=NKUJUXUJ3B
Runtime Version=14.0.0
Sealed Resources version=2 rules=13 files=931
Internal requirements count=1 size=188

**Comment by mgallien** [comment]
@MiMoHo any issue would need to be reported there https://github.com/nextcloud/desktop/issues
