### ISSUE TITLE
v3.12.2 crash

### ISSUE THREAD

**Issue by fbosche** [nextcloud-releases/desktop#5]
The desktop version c3.12.2 crashes Explorer on Windows 10. Crash happens when I right-click on any file or folder in explorer. I am now downgrading to v3.12.1 that I hope works.

**Comment by sargue** [comment]
Probably this bug: https://github.com/nextcloud/desktop/issues/6566

**Comment by fbosche** [comment]
Indeed. I confirm v3.12.1 works fine.

**Comment by fbosche** [comment]
I close this now
