### ISSUE TITLE
Desktop version 3.9.4 prompts for upgrade to unsupported version

### ISSUE THREAD

**Issue by fearlessforhim** [nextcloud-releases/desktop#7]
Nextcloud desktop 3.10.0 removed support for Mac OS 11 and earlier. Version 3.9.4 supports Mac OS 10.14 and later. Anyone using Mac OS 11 must use 3.9.4 but will get periodic pop-ups to upgrade to the latest version. Going through with the installation causes Nextcloud desktop to stop functioning due to lack of support.

If possible, please patch 3.9.4 to not prompt for updates that are unsupported on the current OS.

System Information
Nextcloud version: 3.9.4

OS: Mac OS 11.7.10 (Big Sur)
MacBook Pro (Retina, 13-inch, Late 2013)
2.6 GHz Dual-Core Intel Core i5

**Comment by mgallien** [comment]
we put back compatibility with macOS 11
closing for now
