### ISSUE TITLE
Broken link to Linux AppImage for 3.13.0

### ISSUE THREAD

**Issue by alametti** [nextcloud-releases/desktop#8]
The link currently found on the Downloads page (`https://nextcloud.com/install/`) currently points to `https://github.com/nextcloud-releases/desktop/releases/latest/download/Nextcloud-3.12.3-x86_64.AppImage`, which is a broken link.

The correct link should be `https://github.com/nextcloud-releases/desktop/releases/download/v3.13.0/Nextcloud-3.13.0-x86_64.AppImage`

**Comment by mgallien** [comment]
was temporary
is fixed now
